# Your Solution

# Deployment and Service for PostgreSQL Database
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "assignment9_2_user"
        - name: POSTGRES_PASSWORD
          value: "Xw4oTggfRZpgEL6UKfOw1P4pHKvjknKC"
        - name: POSTGRES_DB
          value: "assignment9_2"
---

# Deployment and Service for Book Catalog Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
  labels:
    app: book-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: ${CONTAINER_REGISTRY}/book_catalog:latest
        ports:
        - containerPort: 5051
        env:
        - name: DATABASE_URL
          value: "postgresql://assignment9_2_user:Xw4oTggfRZpgEL6UKfOw1P4pHKvjknKC@dpg-crpvv7rv2p9s738dgf60-a.oregon-postgres.render.com/assignment9_2"

---
# Deployment and Service for Inventory Management Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
  labels:
    app: inventory-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: ${CONTAINER_REGISTRY}/inventory_management:latest
        ports:
        - containerPort: 5052
        env:
        - name: DATABASE_URL
          value: "postgresql://assignment9_2_user:Xw4oTggfRZpgEL6UKfOw1P4pHKvjknKC@dpg-crpvv7rv2p9s738dgf60-a.oregon-postgres.render.com/assignment9_2"